### ISSUE TITLE
ReferenceError: fetch is not defined in compiled TypeScript

### ISSUE THREAD

**Issue by snagy22000** [zya/litellmjs#14]
**Title:** ReferenceError: fetch is not defined in compiled TypeScript

**Labels:** bug, server, typescript

**Describe the bug**
When running the compiled TypeScript code, a `ReferenceError` is thrown indicating that `fetch` is not defined.

**To Reproduce**
1. Compile the TypeScript code to JavaScript
2. Run the compiled JavaScript code
3. See error in the server logs

**Expected behavior**
The `fetch` function should be defined and the code should run without errors..

**Error message**
```
ReferenceError: fetch is not defined
    at /usr/src/app/node_modules/litellm/dist/src/handlers/ollama.js:94:9
    at Generator.next (<anonymous>)
    at /usr/src/app/node_modules/litellm/dist/src/handlers/ollama.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/src/app/node_modules/litellm/dist/src/handlers/ollama.js:4:12)
    at getOllamaResponse (/usr/src/app/node_modules/litellm/dist/src/handlers/ollama.js:93:12)
    at /usr/src/app/node_modules/litellm/dist/src/handlers/ollama.js:113:27
    at Generator.next (<anonymous>)
    at /usr/src/app/node_modules/litellm/dist/src/handlers/ollama.js:8:71
    at new Promise (<anonymous>)
```

**Additional context**
This error occurs in the `ollama.js` file in the `litellm` module. It seems that the `fetch` function is not defined in this context.

**Comment by zya** [comment]
@snagy22000 what version of node are you using?
can you also elaborate on what you mean by `Compile the TypeScript code to JavaScript`? What are the steps you are taking and what is your use-case?
